//
//  YVTheme.h
//  YourView
//
//  Created by bliss_ddo on 2019/4/27.
//  Copyright © 2019 bliss_ddo. All rights reserved.
//

#ifndef YVTheme_h
#define YVTheme_h


#define YVTHEME_TITLEBAR_BACKGROUNDCOLOR RGBCOLOR(240,240,240).CGColor
#define YVTHEME_TITLEBAR_BORDERCOLOR RGBCOLOR(172,172,172).CGColor
#define YVTHEME_NODE_HOVERBORDERCOLOR RGBCOLOR(80,131,219)
#define YVTHEME_NODE_HOVERBORDERNORMALCOLOR RGBCOLOR(218,218,218)

#define YVTHEME_NODE_HIGHLIGHTCOLOR RGBCOLOR(206,214,255)
//#define YVTHEME_NODE_HIGHLIGHTCOLOR [NSColor blueColor]


//#define YVTHEME_SCNVIEW_BACKGROUNDCOLOR RGBCOLOR(225,227,230)
#define YVTHEME_SCNVIEW_BACKGROUNDCOLOR [NSColor blackColor]


#endif /* YVTheme_h */
